-- Seed inicial de modulos para DMT Web-Labs - Induccion SMT

insert into public.modules (module_number, title, subtitle, objective, key_message, status) values
(1, 'Induccion operacional', 'Sistema de Monitoreo Telematico - Ley 21.378 - Violencia Intrafamiliar', 'Presentar la finalidad protectora del sistema y el rol de apoyo visual para operadores.', 'La unidad protege a la victima y supervisa el cumplimiento de medidas cautelares mediante monitoreo territorial preventivo.', 'published'),
(2, 'Marco normativo y objetivo del monitoreo', 'Base juridica y sentido preventivo del sistema', 'Explicar la relacion entre Ley 21.378, Decreto N 19 y objetivo preventivo.', 'La tecnologia esta al servicio de la finalidad protectora de la medida.', 'published'),
(3, 'Marco juridico-operacional', 'Relacion entre la ley, el reglamento y el protocolo', 'Ordenar la relacion entre norma legal, reglamento y protocolo operacional.', 'La ley manda, el reglamento ordena y el protocolo operacionaliza.', 'published'),
(4, 'Principios operacionales fundamentales', 'Criterios que ordenan la toma de decisiones', 'Presentar los criterios de proteccion, finalidad, contexto, trazabilidad, gradualidad y objetividad.', 'No todas las alarmas son iguales; todas se analizan segun riesgo, continuidad y contexto.', 'published'),
(5, 'Actores del sistema y flujo de coordinacion', 'Operacion integrada con visualizacion de datos y coordinacion interinstitucional', 'Identificar actores y flujo operacional entre Central, victima, PSC, CENCO, Carabineros, soporte tecnico y tribunal.', 'La operacion integra visualizacion de datos, georreferenciacion y coordinacion interinstitucional.', 'published'),
(6, 'Conceptos operacionales criticos', 'Terminos que el operador debe dominar', 'Definir ultimo trazo valido, zona de exclusion, pre-exclusion, halo y triangulacion.', 'Siempre se analiza fecha, hora, continuidad, desplazamiento y contexto.', 'published'),
(7, 'Logica operacional general', 'Secuencia base para el tratamiento de una alarma', 'Guiar la respuesta: verificar riesgo, clasificar evento, contactar, escalar y documentar.', 'Primero se comprende el evento; luego se decide la respuesta.', 'published'),
(8, 'Tipos de alarma tecnica', 'Eventos orientados a continuidad operativa y soporte', 'Clasificar alarmas tecnicas de energia, senal, ubicacion, integridad fisica y perifericos.', 'Estas alarmas pueden escalar si afectan la capacidad de proteccion.', 'published'),
(9, 'Tipos de alarma de riesgo y mixtas', 'Eventos que pueden comprometer directamente la proteccion de la victima', 'Diferenciar alarmas de riesgo directo y eventos mixtos que evolucionan a riesgo real.', 'La gravedad depende de la cercania, la continuidad y el contexto.', 'published'),
(10, 'Protocolo CENCO y contacto telefonico', 'Escalamiento policial preventivo y comunicacion segura', 'Ordenar contacto con victima, CENCO y PSC cuando corresponda.', 'La comunicacion debe ser calmada, segura, objetiva y trazable.', 'published'),
(11, 'Activacion CENCO y medidas de resguardo', 'Cuando escalar y como comunicar', 'Definir criterios de escalamiento a CENCO y medidas basicas de resguardo para la victima.', 'El escalamiento procede cuando el riesgo o la perdida de control operacional lo justifican.', 'published'),
(12, 'Relacion con el tribunal y documentacion', 'La dimension juridica de la operacion diaria', 'Reforzar documentacion obligatoria, objetividad y consistencia de informes.', 'Lo no registrado, no existe operativamente.', 'published'),
(13, 'Criterios del operador y principio central', 'Como debe pensar y actuar el operador', 'Promover verificacion, lectura de trazos, contexto y escalamiento proporcional.', 'Comprender el evento para decidir la respuesta mas pertinente.', 'published'),
(14, 'Rol hibrido de la unidad', 'Tecnologia, operacion y derecho al servicio de la proteccion', 'Integrar evidencia tecnica, decision operativa y finalidad juridica.', 'La unidad integra evidencia tecnica, decision operativa y finalidad juridica para proteger a la victima.', 'published');

insert into public.templates (title, category, body, legal_note, active) values
('Registro minimo de alarma', 'documentacion', 'Se verifica tipo de alarma, fecha, hora, ultimo trazo valido, distancia entre victima y PSC, continuidad de senal y contexto operacional. Se deja registro en sistema y se mantiene seguimiento segun protocolo.', 'Usar solo con datos reales en sistemas oficiales autorizados.', true),
('Contacto con victima sin respuesta', 'contacto', 'Se intenta contacto telefonico con la victima en numeros disponibles, sin respuesta. Se verifica ultimo trazo valido y contexto de riesgo. Se mantiene monitoreo y se evalua escalamiento segun continuidad, cercania y tipo de alarma.', 'No incorporar datos personales en esta web-lab.', true),
('Activacion CENCO preventiva', 'cenco', 'Por evento con riesgo de proximidad/exclusion o perdida de control operacional, se informa a CENCO con antecedentes objetivos disponibles: tipo de alarma, hora, ubicacion referencial autorizada, estado de contacto y medidas de resguardo indicadas.', 'La informacion sensible debe enviarse solo por canales institucionales definidos.', true),
('Cierre operacional sin riesgo observado', 'cierre', 'Se revisan trazos, distancia, continuidad y contexto. No se observan antecedentes actuales de riesgo inmediato. Se registra actuacion y se mantiene monitoreo regular.', 'El cierre debe ajustarse a protocolo vigente y criterio de turno.', true);

