-- Seed inicial de módulos para DMT Web-Labs - Inducción S.M.T.

insert into public.modules (module_number, title, subtitle, objective, key_message, status) values
(1, 'Inducción operacional', 'Sistema de Monitoreo Telemático - Ley 21.378 - Violencia Intrafamiliar', 'Presentar la finalidad protectora del sistema y el rol de apoyo visual para operadores.', 'La unidad protege a la víctima y supervisa el cumplimiento de medidas cautelares mediante monitoreo territorial preventivo.', 'published'),
(2, 'Marco normativo y objetivo del monitoreo', 'Base jurídica y sentido preventivo del sistema', 'Explicar la relación entre Ley 21.378, Decreto N° 19 y objetivo preventivo.', 'La tecnología está al servicio de la finalidad protectora de la medida.', 'published'),
(3, 'Marco jurídico-operacional', 'Relación entre la ley, el reglamento y el protocolo', 'Ordenar la relación entre norma legal, reglamento y protocolo operacional.', 'La ley manda, el reglamento ordena y el protocolo operacionaliza.', 'published'),
(4, 'Principios operacionales fundamentales', 'Criterios que ordenan la toma de decisiones', 'Presentar los criterios de protección, finalidad, contexto, trazabilidad, gradualidad y objetividad.', 'No todas las alarmas son iguales; todas se analizan según riesgo, continuidad y contexto.', 'published'),
(5, 'Actores del sistema y flujo de coordinación', 'Operación integrada con visualización de datos y coordinación interinstitucional', 'Identificar actores y flujo operacional entre Central, víctima, PSC, CENCO, Carabineros, soporte técnico y tribunal.', 'La operación integra visualización de datos, georreferenciación y coordinación interinstitucional.', 'published'),
(6, 'Conceptos operacionales críticos', 'Términos que el operador debe dominar', 'Definir último trazo válido, zona de exclusión, pre-exclusión, halo y triangulación.', 'Siempre se analiza fecha, hora, continuidad, desplazamiento y contexto.', 'published'),
(7, 'Lógica operacional general', 'Secuencia base para el tratamiento de una alarma', 'Guiar la respuesta: verificar riesgo, clasificar evento, contactar, escalar y documentar.', 'Primero se comprende el evento; luego se decide la respuesta.', 'published'),
(8, 'Tipos de alarma técnica', 'Eventos orientados a continuidad operativa y soporte', 'Clasificar alarmas técnicas de energía, señal, ubicación, integridad física y periféricos.', 'Estas alarmas pueden escalar si afectan la capacidad de protección.', 'published'),
(9, 'Tipos de alarma de riesgo y mixtas', 'Eventos que pueden comprometer directamente la protección de la víctima', 'Diferenciar alarmas de riesgo directo y eventos mixtos que evolucionan a riesgo real.', 'La gravedad depende de la cercanía, la continuidad y el contexto.', 'published'),
(10, 'Protocolo CENCO y contacto telefónico', 'Escalamiento policial preventivo y comunicación segura', 'Ordenar contacto con víctima, CENCO y PSC cuando corresponda.', 'La comunicación debe ser calmada, segura, objetiva y trazable.', 'published'),
(11, 'Activación CENCO y medidas de resguardo', 'Cuándo escalar y cómo comunicar', 'Definir criterios de escalamiento a CENCO y medidas básicas de resguardo para la víctima.', 'El escalamiento procede cuando el riesgo o la pérdida de control operacional lo justifican.', 'published'),
(12, 'Relación con el tribunal y documentación', 'La dimensión jurídica de la operación diaria', 'Reforzar documentación obligatoria, objetividad y consistencia de informes.', 'Lo no registrado, no existe operativamente.', 'published'),
(13, 'Criterios del operador y principio central', 'Cómo debe pensar y actuar el operador', 'Promover verificación, lectura de trazos, contexto y escalamiento proporcional.', 'Comprender el evento para decidir la respuesta más pertinente.', 'published'),
(14, 'Rol híbrido de la unidad', 'Tecnología, operación y derecho al servicio de la protección', 'Integrar evidencia técnica, decisión operativa y finalidad jurídica.', 'La unidad integra evidencia técnica, decisión operativa y finalidad jurídica para proteger a la víctima.', 'published');

insert into public.templates (title, category, body, legal_note, active) values
('Registro mínimo de alarma', 'documentación', 'Se verifica tipo de alarma, fecha, hora, último trazo válido, distancia entre víctima y PSC, continuidad de señal y contexto operacional. Se deja registro en sistema y se mantiene seguimiento según protocolo.', 'Usar solo con datos reales en sistemas oficiales autorizados.', true),
('Contacto con víctima sin respuesta', 'contacto', 'Se intenta contacto telefónico con la víctima en números disponibles, sin respuesta. Se verifica último trazo válido y contexto de riesgo. Se mantiene monitoreo y se evalúa escalamiento según continuidad, cercanía y tipo de alarma.', 'No incorporar datos personales en esta web-lab.', true),
('Activación CENCO preventiva', 'cenco', 'Por evento con riesgo de proximidad/exclusión o pérdida de control operacional, se informa a CENCO con antecedentes objetivos disponibles: tipo de alarma, hora, ubicación referencial autorizada, estado de contacto y medidas de resguardo indicadas.', 'La información sensible debe enviarse solo por canales institucionales definidos.', true),
('Cierre operacional sin riesgo observado', 'cierre', 'Se revisan trazos, distancia, continuidad y contexto. No se observan antecedentes actuales de riesgo inmediato. Se registra actuación y se mantiene monitoreo regular.', 'El cierre debe ajustarse a protocolo vigente y criterio de turno.', true);
